Stat svc
AntonFeklichev/java-explore-with-me pull request #6
Opened 2023-04-17 13:23 UTC by AntonFeklichev

2023-04-18 03:01 UTC, sergeymamonov requested changes
Файл .gitignore должен быть только один в проекте и лежать в корне. Все остальные файлы .gitignore лишние. Поиск показывает (Ctrl + O Tab -> Files), что в проекте их 5 штук.

Папка src лишняя в модуле explore-with-me-stats. Это родительский модуль, в нем должны быть только подмодули.

2023-04-18 03:01 UTC, sergeymamonov commented on explore-with-me-stats/explore-with-me-stats-service/src/main/java/ru/practicum/stats/viewstats/service/ViewStatsService.java
> +        if (requestDto.getUris() == null || requestDto.getUris()
Сейчас ветки if/else занимают много строк, от этого читать код непросто. Я бы сделал код веток отдельными методами или через переменные, чтобы вынести код из веток if/else и между операторами if/else было бы 1-3 строки. Так код будет легче читать.

2023-04-18 09:01 UTC, AntonFeklichev commented on explore-with-me-stats/explore-with-me-stats-service/src/main/java/ru/practicum/stats/viewstats/service/ViewStatsService.java
> +        if (requestDto.getUris() == null || requestDto.getUris()
Исправил, надеюсь не слишком много методов сделал

2023-04-18 09:02 UTC, AntonFeklichev commented
@sergeymamonov , спасибо за замечания, все исправил

2023-04-19 15:02 UTC, sergeymamonov approved these changes

2023-04-19 16:23 UTC, merged