Main svc v1
AntonFeklichev/java-explore-with-me pull request #7
Opened 2023-05-02 20:13 UTC by AntonFeklichev

2023-05-06 14:22 UTC, sergeymamonov requested changes
В модуле explore-with-me-main находится еще один модуль explore-with-me-main-server. Это избыточно. Одного модуля здесь достаточно.
Проверьте все switch на наличие ветки default. В новых версиях Java можно сделать без default, но в Java 11 рекомендовал бы добавлять default.

И рекомендую сделать информативное описание вашего проекта.

2023-05-06 14:22 UTC, sergeymamonov commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/event/service/AdminEventService.java
> +        }
Предложил бы добавить default, на случай получения неподдерживаемого статуса.

2023-05-06 14:22 UTC, sergeymamonov commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
Это исключение где-то используется?

2023-05-06 14:22 UTC, sergeymamonov commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/exception/InvalidEventDateException.java
> +public class InvalidEventDateException extends ConflictException {
Используется?

2023-05-06 14:22 UTC, sergeymamonov commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/exceptionhandler/DefaultExceptionHandler.java
> +    public ResponseEntity<ApiError> handleRuntimeException(final RuntimeException e) {
Кажется странным RuntimeException и BAD_REQUEST. Может INTERNAL_ERROR?

2023-05-06 14:22 UTC, sergeymamonov commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/participationrequest/service/PrivateParticipationRequestService.java
> +        if (event.getState() != EventState.PUBLISHED) {
А почему не equals?

2023-05-06 17:01 UTC, AntonFeklichev commented on explore-with-me-main/explore-with-me-main-server/src/main/java/ru/practicum/ewm/main/server/category/dto/CreateCategoryRequestDto.java
> +    public CreateCategoryRequestDto(
Да, я пробовал, но, к сожалению, без явного указания `@JsonCreator` jackson не десериализует корректно объекты классов с одним `final` полем: вот issue об этом - https://github.com/FasterXML/jackson-module-parameter-names/issues/38

2023-05-07 12:20 UTC, sergeymamonov approved these changes

2023-05-07 20:41 UTC, merged